import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import RootClientLayout from "./RootClientLayout";  // Import the client layout component
import dynamic from "next/dynamic";

// Server-side logic (no hooks)
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Yashwanth",
  description: "Generated by Yashwanth",
};


const ScrollToTop = dynamic(() => import('@/components/common/ScrollToTop'));
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning className="dark" >
      <body  className={`${geistSans.variable} ${geistMono.variable} antialiased `}>
     
      <RootClientLayout>
      {children}  
    </RootClientLayout>
    <ScrollToTop />
      </body>
    </html>
  );
}
